version: '3.8'
services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  nestjs:
    build:
      context: ./nestjs
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - fastapi
