# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: location.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x08location\"\x1d\n\x0fLocationRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest\"Q\n\x10LocationResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\"E\n\x14LocationListResponse\x12-\n\tlocations\x18\x01 \x03(\x0b\x32\x1a.location.LocationResponse2\xa0\x01\n\x0fLocationService\x12\x44\n\x0bGetLocation\x12\x19.location.LocationRequest\x1a\x1a.location.LocationResponse\x12G\n\rListLocations\x12\x16.location.EmptyRequest\x1a\x1e.location.LocationListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONREQUEST']._serialized_start=28
  _globals['_LOCATIONREQUEST']._serialized_end=57
  _globals['_EMPTYREQUEST']._serialized_start=59
  _globals['_EMPTYREQUEST']._serialized_end=73
  _globals['_LOCATIONRESPONSE']._serialized_start=75
  _globals['_LOCATIONRESPONSE']._serialized_end=156
  _globals['_LOCATIONLISTRESPONSE']._serialized_start=158
  _globals['_LOCATIONLISTRESPONSE']._serialized_end=227
  _globals['_LOCATIONSERVICE']._serialized_start=230
  _globals['_LOCATIONSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
